name: TWRP11 Builder

on:
  #  release:
  #    types: [published]
  #  push:
  #    branches:
  #      - master
  #    paths:
  #      - '.config'
  #  schedule:
  #    - cron: 0 8 * * 5
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      crypto:
        description: "是否禁用加密模块，true or false"
        required: false
        default: "false"
  # watch:
  #   types: [started]

env:
  Rec_name: TWRP11
  Rec_ver: 3.5.2
  Rec_url: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11
  device: elish
  DT_url: https://github.com/AngryBeeSec/android_xiaomi_elish_twrp
  DT_path: device/xiaomi/elish
  target: recoveryimage
  WorkSpace: WorkSpace
  TZ: Asia/Shanghai
  Author: zerorooot
  Enable_cache: false
  Enable_ccache: true
  Delete_old: false

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initializing environment
        run: |
          sudo -E apt-get clean
          sudo -E apt-get -qq update
          sudo apt install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip jq
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          git config --global user.name "RC1844"
          git config --global user.email "1844766234@qq.com"
        #  git clone https://gitlab.com/OrangeFox/misc/scripts --depth=1 --single-branch
        #  cd scripts
        # sudo -E bash setup/android_build_env.sh
        # sudo -E bash setup/install_android_sdk.sh

      - name: Sync recovery source
        run: |
          mkdir ${{env.WorkSpace}}
          cd ${{env.WorkSpace}}
          repo init -u ${{env.Rec_url}} --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
          repo sync -j4

      - name: Sync device tree
        run: |
          cd ${{env.WorkSpace}}
          git clone ${{ env.DT_url }} --depth=1 --single-branch ${{ env.DT_path }}
        #  cd ${{ env.DT_path }}
       #   sed -i 's/vendor\/omni/vendor\/twrp/g' twrp_${{ env.device }}.mk
          # rm -r recovery/root/system/lib64
          # rm -r recovery/root/system/bin

      - name: Disable Crypto
        if: (github.event.inputs.crypto == 'true' && github.event.inputs.crypto  != 'false') || contains(github.event.action, 'crypto')
        run: |
          cd ${{env.WorkSpace}}/${{ env.DT_path }}
          sed -i 's/TW_INCLUDE_CRYPTO := true/TW_INCLUDE_CRYPTO := false/g' BoardConfig.mk
          sed -i 's/TW_INCLUDE_CRYPTO_FBE := true/TW_INCLUDE_CRYPTO_FBE := false/g' BoardConfig.mk


      - name: Setup ccache
        uses: alexjurkiewicz/setup-ccache@master
        if: env.Enable_ccache == 'true' && !cancelled()
        with:
          max-size: 5G
          extra-config: |
            keep_comments_cpp = true

      - name: Building ${{env.Rec_name}}
        run: |
          cd ${{env.WorkSpace}}
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch twrp_${{ env.device }}-eng
          repo sync -j4
          mka ${{env.target}}
        shell: bash

      - name: Get info
        id: info
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m-%d-%H-%M")"
          echo "::set-output name=OutFolder::"${{env.WorkSpace}}/out/target/product/${{ env.device }}""
        shell: bash

      - name: Show out tree
        run: |
          cd ${{steps.info.outputs.OutFolder}}
          sudo zip -r9 ${{env.Rec_name}}_for_${{ env.device }}_by_${{ env.Author }}.zip recovery.img
          tree -C -L 5

      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        # if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: ${{env.Rec_name}}_for_${{ env.device }}-${{ github.run_id }}
          path: ${{steps.info.outputs.OutFolder}}/*.img

      - name: Upload Release
        uses: softprops/action-gh-release@master
        with:
          files: |
            ${{steps.info.outputs.OutFolder}}/${{env.Rec_name}}_for_${{ env.device }}_by_${{ env.Author }}.zip
            ${{steps.info.outputs.OutFolder}}/*.img
          name: ${{env.Rec_name}}-${{ env.device }}-${{ github.run_id }}
          tag_name: ${{ env.device }}-${{env.Rec_name}}-${{ steps.info.outputs.date }}
          body: |
            ${{env.Rec_name}}-${{env.Rec_ver}} for ${{ env.device }} build at ${{ steps.info.outputs.date }}
            Download link :https://download.fastgit.org/zerorooot/Actions-Build-TWRP-For-Elish/releases/download/${{ env.device }}-${{env.Rec_name}}-${{ steps.info.outputs.date }}/${{env.Rec_name}}_for_${{ env.device }}_by_${{ env.Author }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TWRP_TOKEN }}
